name: DataFrame Build Test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          make install
          
      - name: Build project
        run: |
          make build

  test:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 2
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # or whatever version you want
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt  # Install your project dependencies
      - name: Run tests
        run: |
          make test

  package:
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 2
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build Deb package
        run: |
          make build-deb
      - name: Check the build directory contents
        run: ls -l build
      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: dataframe-deb
          path: build/dataframe-v2.0.0.deb

  lint:
    runs-on: ubuntu-latest
    needs: package
    timeout-minutes: 2
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install lintian
        run: sudo apt-
